apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mongo-secret
spec:
  encryptedData:
    mongo-password: AgA+UyDE4DpjbClL6TjC3CvbhQD0ndxtIjsgASKVakTKQiwqgNVXak+KilTaVvP5jsOS19jmq7+UWk9P/zQHT32homRHX0RqxOdfWdiJLSvWr0yuDmqHzVCJjpImxp+wY4fw2BMzPz5E+Un0jmvNSB+Ce96EJXosLmSrS4ZP31Tx2yf0eF/67bxKC3rGbnhEsFf/nVmT5F2/9yD9fDCOcj0ope7PvsNMX7XX1FP0ORuzYyyFmsb1j5c55wqeCuO+8rnSPsqbQCaSAPWgHtQkUi38MkNg1tcGH8Xy0qKKDuH0/R7m4yL8qLapzpPbhMdSg5BZBcGzqD/mo1zS+ww/Miyy8UFBSETQnRL5QYC/OyNTNBDyJxs033qPk4WaInsfgtrFUZ1v2eSuoSsFQzC1G0JmKDTztYlsywLK2XoBM6UkpI5S5euGYqwtInDQel39unEFyIIAHFKXAFxslqRN9aXh+pTdamrUBcZ0EnNyPmyluj0KHazOhSwHpZQFtyEbwrLkLCasZIA2zZlcluZ4LzN3JGKnXsU3OKIvGZc6M28YyBfET30MpgIT1jOTmkLbmvqSwZlsmS1ebvwgUovzHzLVfldHtje+FeQVUziXBzpOncZDgzWHFDu1CAytcfS9L/sQrnQwFROrqbiBKWyIUOBmPWy5I5P1tIpat3E+9YSezVnkH8wNffKFdePQHgs2zVKApEtp70s8fjQLHyjy
    mongo-user: AgAazSwQVA0YS5fgAPfC/wHkBibpGUy/2fiyoDGgDVz6sDqmy7O2nQpIMzhkNrGnQ9iMFwWa9YBIPofQnOxwp4top81zLM8PCHYBY7eyyb786IHNVT6MD1YpLQ1c/m9jn8SXoRr3vhyUrRCCjz0Bx31wXSXcQz3urL8HksJpVfc26Nzj9Nh93Ar+iSjbxw7+0OJnTL0QNzlHI1Lvqz3+zyb9dVhacRvVnn3Evl/OHAP54Cw9ujDIpM30Lk3eH/mrkFf98bLTNgB/BLqFqqy0qcEGJy0I8OCR4MjuMzEqdP3m683aRWecT0LT4K9m6USGxTxzEQ+pUU7G/fegburzZdIoVZuPZMz8XVctg+P/BSPTiCGQXiy4jZ7RA1jrzw1niOi9WzoTUVRV3CKBoV4VgsJ0BWhc21JOmO4U3ZqRZBdaj/SRJslp5FdX8OJIgX82R9Tw5XVMK2Tg5xWc3XG1P+ryWGXd9hlv1HiCRk0/Z8nedaUz70pn1woudvXudDh42EUG3H3YWVyKxO2684skbEI6kfgfi7n2VzAnwZhf+BnD2xyPPxOpB65Alo/YhMgEQwgzwPtETqMLzWDBkNTBwMsEXDmBa/ugq33XKDQGAx12kwxJquoANHd/HmTo/ggj13rerZsYbANzCZT4ew4JVoqj64Iw5+NVD4CGMlR1dqAmXOTnvzlO+/OeYGmHp40E5ci8Wqp9tRH8JNM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mongo-secret
    type: Opaque
